// Get All Features
export const FEATURE_LIST_REQUEST = 'FEATURE_LIST_REQUEST'
export const FEATURE_LIST_SUCCESS = 'FEATURE_LIST_SUCCESS'
export const FEATURE_LIST_FAIL = 'FEATURE_LIST_FAIL'

// Get Single Feature
export const FEATURE_DETAILS_REQUEST = 'FEATURE_DETAILS_REQUEST'
export const FEATURE_DETAILS_SUCCESS = 'FEATURE_DETAILS_SUCCESS'
export const FEATURE_DETAILS_FAIL = 'FEATURE_DETAILS_FAIL'

// Set Feature State
export const FEATURE_SET_STATE_REQUEST = 'FEATURE_SET_STATE_REQUEST'
export const FEATURE_SET_STATE_SUCCESS = 'FEATURE_SET_STATE_SUCCESS'
export const FEATURE_SET_STATE_FAIL = 'FEATURE_SET_STATE_FAIL'

// Adjust Traffic
export const FEATURE_ADJUST_TRAFFIC_REQUEST = 'FEATURE_ADJUST_TRAFFIC_REQUEST'
export const FEATURE_ADJUST_TRAFFIC_SUCCESS = 'FEATURE_ADJUST_TRAFFIC_SUCCESS'
export const FEATURE_ADJUST_TRAFFIC_FAIL = 'FEATURE_ADJUST_TRAFFIC_FAIL'

// Reset
export const FEATURE_RESET = 'FEATURE_RESET'
